# Welcome to Jekyll!
#
# This con fig file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Grape Vinyl
email: john.b.boeve@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to The Grape Vinyl! Your one stop shop for a review
  of the lastest movies I've seen using my MoviePass Card.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: viedubonteco
github_username:  JohnBoeve

# Build settings
markdown: kramdown
