# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The GrapeVinyl
email: john.b.boeve@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the GrapeVinyl! This site has a proud less than 24 hour history of being a site dedicated to something! 
  Due to it's name, I would guess that it is a music critique site, but time will tell.
baseurl: "thegrapevinyl.com" # the subpath of your site, e.g. /blog
url: "http://www.thegrapevinyl.com" # the base hostname & protocol for your site
twitter_username: sunnysideup
github_username:  JohnBoeve

# Build settings
markdown: kramdown
